import localFont from "next/font/local";
import "./globals.css";

const display = localFont({
  src: [
    { path: "../../public/fonts/DesktopFonts-Söhne-Buch.otf", weight: "400 " },
  ],
});

export const metadata = {
  title: "Robert Lindgren",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const bodyClass = `${display.className}`;
  return (
    <html lang="en">
      <body className={bodyClass}>{children}</body>
    </html>
  );
}
